module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introduzione',
      link: { type: 'doc', id: 'intro/index' },
      items: ['intro/moduli', 'intro/requisiti', 'intro/stabilita', 'intro/roadmap'],
    },
    {
      type: 'category',
      label: 'Server owner',
      link: { type: 'doc', id: 'server-owner/index' },
      items: [
        'server-owner/installazione',
        'server-owner/configurazione',
        'server-owner/personaggi',
        'server-owner/economia',
        'server-owner/lavori',
        'server-owner/organizzazioni',
        'server-owner/permessi',
        'server-owner/pannello-staff',
        'server-owner/banca',
        'server-owner/temi',
        'server-owner/manutenzione',
      ],
    },
    {
      type: 'category',
      label: 'Sviluppatori',
      link: { type: 'doc', id: 'sviluppatori/index' },
      items: [
        'sviluppatori/quickstart',
        'sviluppatori/registro-servizi',
        {
          type: 'category',
          label: 'Servizi',
          items: [
            'sviluppatori/servizi/economia',
            'sviluppatori/servizi/personaggi',
            'sviluppatori/servizi/lavori',
            'sviluppatori/servizi/organizzazioni',
            'sviluppatori/servizi/permessi',
            'sviluppatori/servizi/staff',
            'sviluppatori/servizi/dati-mod',
          ],
        },
        'sviluppatori/eventi',
        'sviluppatori/client-api',
        'sviluppatori/tema-gui',
        'sviluppatori/api-banca',
        'sviluppatori/build',
      ],
    },
    {
      type: 'category',
      label: 'Riferimento',
      link: { type: 'doc', id: 'riferimento/index' },
      items: [
        'riferimento/nodi-permesso',
        'riferimento/eventi',
        'riferimento/glossario',
        'riferimento/changelog',
      ],
    },
  ],
};
